### ISSUE TITLE
kontrolka daty

### ISSUE THREAD

**Issue by sinnetradek** [siudeks/sin-net-reports#25]
Inline Calendar with 6 weeks display by default

z strony https://developer.microsoft.com/en-us/fluentui#/controls/web/calendar

**Comment by siudeks** [comment]
Takie coś chcesz? Kalendarz bez edycji wartości z klawiatury?
To jest dokładnie to co wybrałeś jako kalendarz ...
![image](https://user-images.githubusercontent.com/3256574/98736985-e0060900-23a5-11eb-9832-7b357536fbfb.png)

**Comment by siudeks** [comment]
Zrobione. Jeżeli nie działa - skomentuj
